# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pjimenez <pjimenez@student.42malaga.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/30 11:53:25 by pjimenez          #+#    #+#              #
#    Updated: 2023/11/30 13:16:30 by pjimenez         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = push_swap
INCLUDE = include/
LIBFT = libft
UTILS_DIR = utils/
OPERATIONS_DIR = operations/
STACK_DIR = stack/
CC = gcc
CFLAGS	= -Wall -Werror -Wextra -I

UTILS = find_limits utils
OPERATIONS = move_fts push_fts reverse_rotate_fts rotate_fts swap_fts
STACK = set_nodes stack_fts